version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"
    networks:
      - fruit-network

  fruit-month-price-service:
    build:
      context: ./fruit-month-price-service
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - SPRING_CLOUD_ZOOKEEPER_CONNECT_STRING=zookeeper:2181
    depends_on:
      - zookeeper
    networks:
      - fruit-network

  fruit-total-price-service:
    build:
      context: ./fruit-total-price-service
      dockerfile: Dockerfile
    ports:
      - "8100:8100"
    environment:
      - SPRING_CLOUD_ZOOKEEPER_CONNECT_STRING=zookeeper:2181
    depends_on:
      - zookeeper
      - fruit-month-price-service
    networks:
      - fruit-network

  frontend:
    image: nginx:alpine
    container_name: fruit-price-frontend
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
    depends_on:
      - fruit-month-price-service
      - fruit-total-price-service
    networks:
      - fruit-network

networks:
  fruit-network:
    driver: bridge
